from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from app.agents.style_analyzer import StyleAnalyzer
from config import settings

KNOWLEDGE_BASE_DIR = settings.BASE_DIR.parent / "knowledge_base"


def _load_json(name: str) -> dict[str, Any]:
    path = KNOWLEDGE_BASE_DIR / name
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text("utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


class TemplateExporter:

    def export(
        self,
        style_profile: dict[str, Any] | None = None,
        brand_voice: dict[str, Any] | None = None,
        vault_rules: dict[str, Any] | None = None,
    ) -> str:
        brand_voice = brand_voice or _load_json("brand_voice.json")
        lines = [
            "# copywrAIter — Content Template",
            f"Generated: {datetime.now(timezone.utc).isoformat()}",
            "",
            "## Instructions",
            "Fill in the sections below. Use this template to refine your content",
            "prompt in Gemini, ChatGPT, or any LLM before sending to copywrAIter.",
            "",
            "### Topic",
            "[Enter your topic here]",
            "",
            "### Target Platform",
            "[LinkedIn / Blog / Email / Landing Page]",
            "",
            "### Copywriting Framework",
            "[AIDA / PAS / BAB / FAB / THE_4_CS — or leave blank for auto]",
            "",
            "### Hook Type",
            "[Negative / Statistical / Curiosity / Authority / Question-Based — or leave blank for auto]",
            "",
        ]

        if style_profile:
            lines.extend([
                "### Style Profile",
                f"- Avg sentence length: {style_profile.get('avg_sentence_length', 'N/A')} words",
                f"- Emoji density: {style_profile.get('emoji_density', 0)}%",
                f"- Unique word ratio: {style_profile.get('unique_word_ratio', 'N/A')}",
                f"- Tone markers: {json.dumps(style_profile.get('tone_markers', {}))}",
                "",
            ])

        if brand_voice:
            lines.extend([
                "### Brand Voice",
                f"- Tone: {brand_voice.get('tone', {})}",
                f"- Language: {brand_voice.get('language', {})}",
                f"- Post style: {brand_voice.get('post_style', {})}",
                "",
            ])

        if vault_rules:
            lines.extend([
                "### Instruction Vault Rules",
            ])
            for category, rules in vault_rules.items():
                lines.append(f"\n#### {category}")
                if isinstance(rules, list):
                    lines.extend(f"- {r}" for r in rules)
                elif isinstance(rules, str):
                    lines.append(rules)
            lines.append("")

        lines.extend([
            "### Content",
            "[Write your content draft here]",
            "",
            "---",
            "*This template was generated by copywrAIter v1.5*",
        ])

        return "\n".join(lines)

    def export_to_file(
        self,
        filepath: str,
        style_profile: dict[str, Any] | None = None,
        brand_voice: dict[str, Any] | None = None,
        vault_rules: dict[str, Any] | None = None,
    ) -> str:
        content = self.export(style_profile, brand_voice, vault_rules)
        path = settings.BASE_DIR.parent / filepath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return str(path)


template_exporter = TemplateExporter()
